### PR TITLE
feat: use OTP 26 and prepare to tag `3.20.0-emqx-1`

### PR DESCRIPTION
**Pull request by thalesmg**

### CODE REVIEW

**Review by id — APPROVED** [review]

**Comment by thalesmg** [comment]
still have to debug an issue:

```
===> Running provider: shell
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,[]}
===> Stack trace to the error location:
[{rebar_prv_shell,kill_old_user,0,[{file,"rebar_prv_shell.erl"},{line,181}]},
 {rebar_prv_shell,setup_shell,1,[{file,"rebar_prv_shell.erl"},{line,143}]},
 {rebar_prv_shell,shell,1,[{file,"rebar_prv_shell.erl"},{line,123}]},
 {rebar_core,do,2,[{file,"rebar_core.erl"},{line,155}]},
 {rebar3,run_aux,2,[{file,"rebar3.erl"},{line,193}]},
 {rebar3,main,1,[{file,"rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,750}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]}]
```

**Comment by thalesmg** [comment]
Not sure if this is the correct fix, the the shell does start... :thinking: :see_no_evil:

**Comment by thalesmg** [comment]
Apparently this fix is not upstream because it's built and published using OTP 24.  :thinking:

**Review by id — APPROVED** [review]

**Comment by thalesmg** [comment]
tagged `3.20.0-emqx-1`

**Pull request merged**
